import OpenAI from 'openai';
import { NextResponse } from 'next/server';
import { db } from '@/lib/db';

const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY || '',
});

export async function POST(req: Request) {
    try {
        if (!process.env.OPENAI_API_KEY) {
            return NextResponse.json({ error: "Missing OpenAI API Key" }, { status: 500 });
        }

        const body = await req.json();
        const { userInfo, results } = body;

        console.log(`Iniciando análisis unificado (OpenAI) para ${userInfo?.email}`);

        // Construct context from the 3 current tests
        const context = `
            TEST 1: Relaciones (Patrones de Dolor)
            Resultados: ${JSON.stringify(results.relaciones)}

            TEST 2: Heridas Profundas (Somática - Huellas en Mente, Alma y Cuerpo)
            Resultados: ${JSON.stringify(results.heridas_profundas)}

            TEST 3: Heridas Femeninas (Identificando Heridas)
            Resultados: ${JSON.stringify(results.heridas_femeninas)}
        `;

        const prompt = `
            Actúa como **Yelitzé Rangel**: Coach Ancestral, terapeuta sistémica y consteladora familiar.

            **IDENTIDAD Y VOZ:**
            - Tu metodología une lo ancestral, lo somático y lo psicológico. No eres coaching motivacional.
            - Vocabulario obligatorio: Lealtades Invisibles, Memorias del Linaje, Memorias Congeladas, Orden Sistémico, Soberanía Corporal, Fascia.
            - Tono: Empático, sistémico, revelador. Dirígete directamente a ${userInfo.name}.
            - PROHIBIDO: Diagnósticos clínicos, consejos médicos, lenguaje de autoayuda genérico.

            **USUARIO:** ${userInfo.name}
            **DATOS DE LOS 3 TESTS:**
            ${context}

            **MISIÓN:** Integra los hallazgos de los 3 tests en una visión sistémica única. Identifica el patrón común —la Lealtad Invisible o Memoria del Linaje— que conecta relaciones, heridas profundas y heridas femeninas en el cuerpo-linaje de ${userInfo.name}.

            **RESPONDE ÚNICAMENTE CON UN JSON VÁLIDO:**
            {
              "screen_message": "3 párrafos en Markdown para pantalla. Párrafo 1 (**El Patrón del Linaje**): la Lealtad Invisible que conecta los 3 tests. Párrafo 2 (**El Cuerpo Recuerda**): en qué zona física específica vive este patrón y cómo se manifiesta somáticamente. Párrafo 3 (**El Primer Movimiento de Orden**): el paso sistémico inicial de liberación. (máx 200 palabras total)",
              "ritual": "Ritual somático concreto y practicable: una acción con el cuerpo (respiración específica, voz, movimiento) para comenzar a liberar el patrón central. Que sea breve, físico y simbólico a la vez. (máx 50 palabras)",
              "mantra": "Declaración de soberanía en PRIMERA PERSONA y PRESENTE que reprograme la creencia central que conecta los 3 tests. Que resuene como un cimiento, no como afirmación de autoayuda. (máx 15 palabras)",
              "pdf_content": "Contenido completo en Markdown para PDF: bienvenida de Yelitzé a ${userInfo.name}, diagnóstico integrado de los 3 tests con vocabulario sistémico, análisis de la zona corporal afectada, ritual somático, mantra y cierre con invitación al trabajo profundo contigo."
            }
        `;

        const completion = await openai.chat.completions.create({
            model: "gpt-4o-mini",
            messages: [
                { role: "system", content: "Eres Yelitzé Rangel. Responde siempre en formato JSON." },
                { role: "user", content: prompt }
            ],
            response_format: { type: "json_object" },
            temperature: 0.7
        });

        const responseText = completion.choices[0].message.content || '{}';
        const parsedData = JSON.parse(responseText);

        // Save to DB
        const saved = await db.testResult.create({
            data: {
                testTitle: "Diagnóstico Unificado - Activación de Poder",
                score: 0,
                maxScore: 100,
                answers: JSON.stringify(results),
                aiAnalysis: parsedData.screen_message,
                userName: userInfo.name,
                userEmail: userInfo.email
            }
        });

        // --- NEW: Send Email (Like Somatic Test) ---
        const userEmail = userInfo?.email;
        const userName = userInfo?.name || 'Explorador/a';

        if (userEmail && userEmail.includes('@')) {
            try {
                console.log(`[Unified Test Debug] Attempting email to: ${userEmail}, name: ${userName}`);
                const { sendGenericTestEmail } = await import('@/lib/mail');
                const { generateGenericTestPDF } = await import('@/lib/pdf-generator');
                
                // Use the full PDF content generated by AI
                const pdfContent = parsedData.pdf_content || parsedData.screen_message || 'Sin contenido de análisis disponible.';
                const pdfBuffer = await generateGenericTestPDF(userName, 'Diagnóstico Ancestral Completo', pdfContent);
                
                const mailResult = await sendGenericTestEmail({
                    email: userEmail,
                    name: userName,
                    testTitle: 'Tu Diagnóstico Ancestral Completo',
                    analysis: parsedData.screen_message || 'Ver PDF adjunto para el análisis completo.',
                    pdfBuffer
                });
                
                console.log(`[Unified Test Debug] Mail Result:`, JSON.stringify(mailResult));
            } catch (mailError) {
                console.error('[Unified Test Mail Error]:', mailError);
            }
        } else {
            console.warn(`[Unified Test Debug] Skipping email: invalid or missing email address: "${userEmail}"`);
        }

        return NextResponse.json({
            ...parsedData,
            id: saved.id,
            success: true
        });

    } catch (error: any) {
        console.error('API ERROR:', error);
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}
