import * as dotenv from 'dotenv';
import OpenAI from 'openai';
import { sendGenericTestEmail } from '../lib/mail';
import { generateGenericTestPDF } from '../lib/pdf-generator';

dotenv.config({ path: '.env' });
dotenv.config({ path: '.env.local', override: true });

async function test() {
    console.log('Testing Analyze Standalone Logic...');
    
    const userInfo = { name: 'Test User', email: 'kickoffdevelopment@gmail.com' };
    const testId = 'Heridas Femeninas';
    const parsedData = {
        screen_message: 'Mensaje de pantalla de prueba.',
        pdf_content: '# Diagnóstico de Prueba\n\nEste es un contenido de prueba para el PDF.'
    };

    try {
        console.log(`[Standalone Test] Sending email to ${userInfo.email}...`);
        
        // Use the full PDF content generated by AI
        const pdfBuffer = await generateGenericTestPDF(userInfo.name || 'Explorador/a', `Test: ${testId}`, parsedData.pdf_content);
        const result = await sendGenericTestEmail({
            email: userInfo.email,
            name: userInfo.name || 'Explorador/a',
            testTitle: `Tu Diagnóstico: ${testId}`,
            analysis: parsedData.screen_message,
            pdfBuffer
        });
        
        if (result.success) {
            console.log('SUCCESS:', result.data);
        } else {
            console.error('FAILED:', result.error);
        }
    } catch (err) {
        console.error('CRASH:', err);
    }
}

test();
